// Generated by scripts/notioly.py. Do not edit by hand.
export const NOTIOLY_SETS = {
    "people": [
        require("./people/aperitif-with-a-friend.png"),
        require("./people/besties.png"),
        require("./people/coffee-and-friends.png"),
        require("./people/collaboration.png"),
        require("./people/frienship.png"),
        require("./people/high-five.png"),
        require("./people/hug.png"),
        require("./people/in-good-company.png"),
        require("./people/team-spirit.png"),
        require("./people/walking-together.png"),
    ],
} as const;

export type NotiolySet = keyof typeof NOTIOLY_SETS;
