# golangci-lint configuration
run:
  timeout: 5m
  tests: true

linters-settings:
  errcheck:
    check-type-assertions: true

  govet:
    enable-all: true
    disable:
      - shadow
      - fieldalignment
      - composites  # Allow unkeyed composite literals

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec
    - misspell

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec

    # Allow unkeyed composite literals (common in MongoDB bson.E, bson.D, etc.)
    - text: "struct literal uses unkeyed fields"
      linters:
        - govet
        - staticcheck

  max-issues-per-linter: 0
  max-same-issues: 0
