# golangci-lint configuration
# See https://golangci-lint.run/usage/configuration/
version: 2

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - unnamedResult
      - hugeParam
      - rangeValCopy
      - exitAfterDefer
      - whyNoLint
      - singleCaseSwitch
      - commentedOutCode
      - appendAssign
      - unnecessaryBlock
      - redundantSprint
      - unkeyedLiteral
      - unkeyedCompositeLiteral

  # from https://betterstack.com/community/guides/logging/logging-in-go/#best-practices-for-writing-and-storing-go-logs
  sloglint:
    # Enforce not mixing key-value pairs and attributes.
    # Default: true
    no-mixed-args: false
    # Enforce using key-value pairs only (overrides no-mixed-args, incompatible with attr-only).
    # Default: false
    kv-only: true
    # Enforce using attributes only (overrides no-mixed-args, incompatible with kv-only).
    # Default: false
    attr-only: true
    # Enforce using methods that accept a context.
    # Default: ""
    context: all
    # Enforce using static values for log messages.
    # Default: false
    static-msg: true
    # Enforce using constants instead of raw keys.
    # Default: false
    no-raw-keys: true
    # Enforce a single key naming convention.
    # Values: snake, kebab, camel, pascal
    # Default: ""
    key-naming-case: snake
    # Enforce putting arguments on separate lines.
    # Default: false
    args-on-sep-lines: true

  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable-all: true
    disable:
      - shadow
      - fieldalignment

  gocyclo:
    min-complexity: 15

  dupl:
    threshold: 100

  misspell:
    locale: US

  lll:
    line-length: 140

  goimports:
    local-prefixes: github.com/yourusername/Kindred

  goconst:
    min-len: 3
    min-occurrences: 3

  funlen:
    lines: 100
    statements: 50

  nestif:
    min-complexity: 4

  cyclop:
    max-complexity: 15
    skip-tests: true

  revive:
    rules:
      - name: var-naming
        disabled: false
      - name: exported
        disabled: false
      - name: indent-error-flow
        disabled: false
      - name: blank-imports
        disabled: false
      - name: context-as-argument
        disabled: false
      - name: dot-imports
        disabled: false
      - name: error-return
        disabled: false
      - name: error-strings
        disabled: false
      - name: error-naming
        disabled: false
      - name: increment-decrement
        disabled: false
      - name: var-declaration
        disabled: false
      - name: package-comments
        disabled: false
      - name: range
        disabled: false
      - name: receiver-naming
        disabled: false
      - name: time-naming
        disabled: false
      - name: unexported-return
        disabled: false
      - name: indent-error-flow
        disabled: false
      - name: errorf
        disabled: false
      - name: empty-block
        disabled: false
      - name: superfluous-else
        disabled: false
      - name: unused-parameter
        disabled: false
      - name: unreachable-code
        disabled: false
      - name: redefines-builtin-id
        disabled: false

linters:
  disable-all: true
  enable:
    # Enabled by default linters:
    - errcheck        # Checks for unchecked errors
    - gosimple        # Simplify code
    - govet           # Reports suspicious constructs
    - ineffassign     # Detects ineffectual assignments
    - staticcheck     # Go static analysis
    - unused          # Checks for unused constants, variables, functions and types

    # Additional recommended linters:
    - bodyclose       # Checks whether HTTP response body is closed
    - dupl            # Code clone detection
    - funlen          # Detects long functions
    - gochecknoinits  # Checks that no init functions are present
    - goconst         # Finds repeated strings that could be constants
    - gocritic        # Provides diagnostics that check for bugs, performance and style issues
    - gocyclo         # Computes cyclomatic complexity
    - gofmt           # Checks whether code was gofmt-ed
    - goimports       # Checks import statements are formatted
    - goprintffuncname # Checks that printf-like functions are named with f at the end
    - gosec           # Inspects source code for security problems
    - lll             # Reports long lines
    - misspell        # Finds commonly misspelled English words
    - nakedret        # Finds naked returns in functions greater than a specified length
    - nestif          # Reports deeply nested if statements
    - prealloc        # Finds slice declarations that could potentially be preallocated
    - revive          # Fast, configurable, extensible, flexible, and beautiful linter for Go
    - rowserrcheck    # Checks whether Err of rows is checked successfully
    - sloglint        # Ensure consistent code style when using log/slog
    - sqlclosecheck   # Checks that sql.Rows and sql.Stmt are closed
    - stylecheck      # Replacement for golint
    - unconvert       # Remove unnecessary type conversions
    - unparam         # Reports unused function parameters
    - whitespace      # Detection of leading and trailing whitespace

    # Performance linters:
    - cyclop          # Checks function and package cyclomatic complexity

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - funlen
        - goconst
        - gochecknoinits

    # Exclude known linters from partially hard-vendored code
    - path: internal/hmac/
      linters:
        - gosec

    # Exclude lll issues for long lines with go:generate
    - linters:
        - lll
      source: "^//go:generate "

  # Maximum issues count per one linter. Set to 0 to disable. Default is 50.
  max-issues-per-linter: 0

  # Maximum count of issues with the same text. Set to 0 to disable. Default is 3.
  max-same-issues: 0

  # Show only new issues created after git revision
  # new-from-rev: origin/main
