# golangci-lint configuration
version: 2

run:
  timeout: 5m
  tests: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable-all: true
    disable:
      - shadow
      - fieldalignment

  gocyclo:
    min-complexity: 15

  misspell:
    locale: US

  goconst:
    min-len: 3
    min-occurrences: 3

linters:
  disable-all: true
  enable:
    # Default linters (always recommended)
    - errcheck        # Checks for unchecked errors
    - gosimple        # Simplify code
    - govet           # Reports suspicious constructs
    - ineffassign     # Detects ineffectual assignments
    - staticcheck     # Go static analysis
    - unused          # Checks for unused code

    # Additional quality linters
    - bodyclose       # Checks HTTP response body is closed
    - goconst         # Finds repeated strings that could be constants
    - gocyclo         # Computes cyclomatic complexity
    - gosec           # Security issues
    - misspell        # Finds commonly misspelled words
    - unconvert       # Remove unnecessary type conversions
    - unparam         # Reports unused function parameters

issues:
  exclude-rules:
    # Relax linters for test files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - gosec

  max-issues-per-linter: 0
  max-same-issues: 0
