import React from 'react';
import { Image, ImageProps, ImageSource } from 'expo-image';
import { View, StyleSheet } from 'react-native';

interface CachedImageProps extends Omit<ImageProps, 'source'> {
  source: ImageSource;
  fallbackSource?: ImageSource;
  cachePolicy?: 'memory' | 'disk' | 'memory-disk';
  variant?: 'thumbnail' | 'medium' | 'large' | 'original';
}

const CachedImage: React.FC<CachedImageProps> = ({
  source,
  fallbackSource,
  placeholder,
  cachePolicy = 'memory-disk',
  variant = 'medium',
  style,
  ...props
}) => {
  // Optimize URL for CDN and add query parameters for future image processing
  const getOptimizedURL = (url: string) => {
    if (!url || typeof url !== 'string') {
      return url;
    }

    // Skip optimization for external URLs (non-Spaces URLs)
    if (!url.includes('digitaloceanspaces.com') && !url.includes('kindredtodo.com')) {
      return url;
    }

    let optimizedURL = url;

    // Note: CDN URLs are now automatically generated by the backend
    // No need to manually convert URLs here anymore

    // Add variant-specific query parameters for future image processing
    const variants = {
      thumbnail: '?w=300&h=300&q=80&f=webp',
      medium: '?w=800&h=800&q=85&f=webp',
      large: '?w=1200&h=1200&q=90&f=webp',
      original: '' // No processing for original
    };

    // Note: These query parameters are prepared for future image processing service
    // Currently they will be ignored, but the CDN optimization will still work
    const queryParams = variants[variant] || variants.medium;
    
    // Only add query params if URL doesn't already have them
    if (queryParams && !optimizedURL.includes('?')) {
      optimizedURL += queryParams;
    }

    return optimizedURL;
  };

  const optimizedSource = {
    ...source,
    uri: getOptimizedURL((source as any)?.uri || '')
  };

  return (
    <Image
      source={optimizedSource}
      placeholder={placeholder}
      contentFit="cover"
      transition={200}
      cachePolicy={cachePolicy}
      allowDownscaling={true}
      decodeFormat="rgb"
      style={[styles.image, style]}
      {...props}
    />
  );
};

const styles = StyleSheet.create({
  image: {
    width: '100%',
    height: '100%',
  },
});

export default CachedImage;
