#!/usr/bin/env python3
"""Add Notioly illustrations to the app.

  scripts/notioly.py find friend            # search the library by name
  scripts/notioly.py add --set people 130 195 465
  scripts/notioly.py add --set empty-notifications 173
  scripts/notioly.py sync                   # rebuild the registry from the folders

Each Notioly SVG wraps one embedded PNG. `add` extracts it, resizes to 520px, writes
frontend/assets/images/notioly/<set>/<slug>.png and regenerates index.ts, which exposes
NOTIOLY_SETS (set name -> array of require()s) for use with <EmptyIllustration />.
"""
import argparse, base64, os, re, subprocess, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "frontend/assets/images/notioly"
SRC = Path(os.environ.get("NOTIOLY_DIR", "~/Downloads/notioly")).expanduser()
SIZE = "520"


def library():
    # Names look like "130.Frienship.svg" or " 211. Coffee.svg" (stray spaces exist)
    items = {}
    for f in SRC.glob("*.svg"):
        m = re.match(r"\s*(\d+)\.\s*(.+)\.svg$", f.name)
        if m:
            items.setdefault(int(m.group(1)), (m.group(2).strip(), f))
    return items


def slugify(name):
    return re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")


def add(numbers, set_name):
    lib = library()
    dest = OUT / set_name
    dest.mkdir(parents=True, exist_ok=True)
    for n in numbers:
        if n not in lib:
            sys.exit(f"No Notioly graphic numbered {n} in {SRC}")
        name, path = lib[n]
        m = re.search(r"base64,([A-Za-z0-9+/=]+)", path.read_text())
        if not m:
            sys.exit(f"{path.name} has no embedded PNG")
        target = dest / f"{slugify(name)}.png"
        target.write_bytes(base64.b64decode(m.group(1)))
        subprocess.run(["sips", "-Z", SIZE, str(target), "--out", str(target)], check=True, capture_output=True)
        print(f"added {target.relative_to(ROOT)}")
    sync()


def sync():
    sets = {d.name: sorted(d.glob("*.png")) for d in sorted(OUT.iterdir()) if d.is_dir()} if OUT.exists() else {}
    lines = ["// Generated by scripts/notioly.py. Do not edit by hand.", "export const NOTIOLY_SETS = {"]
    for name, files in sets.items():
        lines.append(f'    "{name}": [')
        lines += [f'        require("./{name}/{f.name}"),' for f in files]
        lines.append("    ],")
    lines += ["} as const;", "", "export type NotiolySet = keyof typeof NOTIOLY_SETS;", ""]
    (OUT / "index.ts").write_text("\n".join(lines))
    print(f"wrote {(OUT / 'index.ts').relative_to(ROOT)} ({len(sets)} sets)")


def find(term):
    for n, (name, _) in sorted(library().items()):
        if term.lower() in name.lower():
            print(f"{n}\t{name}")


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    sub = ap.add_subparsers(dest="cmd", required=True)
    a = sub.add_parser("add"); a.add_argument("--set", required=True, dest="set_name"); a.add_argument("numbers", type=int, nargs="+")
    f = sub.add_parser("find"); f.add_argument("term")
    sub.add_parser("sync")
    args = ap.parse_args()
    {"add": lambda: add(args.numbers, args.set_name), "find": lambda: find(args.term), "sync": sync}[args.cmd]()
