name: Build and Push Docker Image

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Create .env file
              run: |
                  cat << EOF > backend/.env
                  # App Configuration
                  APP_PORT=8080

                  # MongoDB Atlas Configuration
                  ATLAS_USER=${{ secrets.ATLAS_USER }}
                  ATLAS_PASS=${{ secrets.ATLAS_PASS }}
                  ATLAS_CLUSTER=${{ secrets.ATLAS_CLUSTER }}
                  ATLAS_ENVIRONMENT=${{ secrets.ATLAS_ENVIRONMENT }}

                  # AWS Configuration
                  AWS_BUCKET_NAME=${{ secrets.AWS_BUCKET_NAME }}
                  AWS_REGION=${{ secrets.AWS_REGION }}
                  AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}

                  # Auth Configuration
                  AUTH_SECRET=${{ secrets.AUTH_SECRET }}
                  EOF

            - name: Log in to the Container registry
              uses: docker/login-action@v3
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
                  tags: |
                      type=ref,event=branch
                      type=ref,event=pr
                      type=semver,pattern={{version}}
                      type=sha,format=short
                      type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                  context: ./backend
                  push: ${{ github.event_name != 'pull_request' }}
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
